version: "2"
sql:
- schema: "../internal/constants/query/schemas"
  queries: "../internal/constants/query/queries"
  engine: "postgresql"
  gen:
    go: 
      package: "db"
      out: "../internal/constants/model/db"
      sql_package: "pgx/v4"
      emit_json_tags: true
      emit_interface: true
      emit_empty_slices: true
      overrides:
        - db_type: "timestamptz"
          go_type: "time.Time"
        - db_type: "uuid"
          go_type: "github.com/google/uuid.UUID"